version: "3.3"

services:
  web-server:
    image: nginx
    container_name: web-server
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    

  api:
    restart: always
    container_name: django-consult-api
    build: .
    expose:
      - "8000"

    networks:
      - consult-subnet

  db:
    image: postgres
    restart: always
    container_name: django-pg
    environment:
      POSTGRES_PASSWORD: admin
    
    networks:
      - consult-subnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

    networks:
      - consult-subnet

networks:
  consult-subnet:
    ipam:
      config:
        - subnet: 10.11.12.0/29