version: "3.3"

services:
  web-server:
    image: nginx
    container_name: web-server
    volumes:
      - "./nginx:/etc/nginx/templates:z"
      - "./dashboard/static:/var/django/static:z"
    ports:
      - "80:80"

    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    - NGINX_PROXY_HOST=api
    - NGINX_PROXY_PORT=8000

    networks:
      - consult-subnet
      
  api:
    restart: always
    container_name: django-consult-api
    build: .
    expose:
      - "8000"
      
    networks:
      - consult-subnet

  db:
    image: postgres
    restart: always
    container_name: django-pg
    environment:
      POSTGRES_PASSWORD: admin
    
    ports:
      - "5432:5432"
      
    networks:
      - consult-subnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

    networks:
      - consult-subnet

networks:
  consult-subnet:
    ipam:
      config:
        - subnet: 10.11.12.0/29